# Start with a minimal pipeline that you can customize to build and deploy your code.


# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Qodana@0
- task: CmdLine@2
  inputs:
    script: 'cp $(Agent.TempDirectory)/qodana/results/qodana.sarif.json $(Agent.TempDirectory)/qodana/results/qodana.sarif'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.TempDirectory)/qodana/results/qodana.sarif'
    ArtifactName: 'CodeAnalysisLogs'
    publishLocation: 'Container'
  
