# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Cache@2
  inputs:
    key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
    path: '$(Agent.TempDirectory)/qodana/cache'
    restoreKeys: |
      "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
      "$(Build.Repository.Name)"
- task: QodanaScan@1
