/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

/**
 * The library.
 */
class Library {
    /**
     * Some library method.
     *
     * @return always returns `true`, never lies.
     */
    fun someLibraryMethod(): Boolean {
        return true
    }
}
