name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Qodana Scan
        # You may pin to the exact commit or the version.
        # uses: JetBrains/qodana-action@9e56346b427d9ed086178d0e60e424c451979261
        uses: JetBrains/qodana-action@v5.0.2
        with:
          # Additional Qodana CLI arguments. Separate multiple arguments with commas (`,`).
          args: >
            --print-problems,
            --fail-threshold,0
